name: cocktail_db_http_using
description: Dart Async lesson
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0
  # обратите внимание - я могу указать зависимость на репозиторий из git с указанием отдельной ветки
  # и конкретный путь к фолдеру/директории
  cocktail_app_models:
    git:
      url: https://github.com/flutter-cats/otus-cocktails-application.git
      ref: master
      path: lesson_03/lesson/cocktail_app_models/

dev_dependencies:
  pedantic: ^1.9.0
  http: ^0.13.0
  build_runner: ^1.12.2
  json_serializable: ^4.0.3