name: lesson_17
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  path_provider: ^2.0.1
  #bloc
  flutter_bloc: ^7.2.0
  hydrated_bloc: ^7.0.1
  replay_bloc: ^0.0.1
  sealed_flutter_bloc: ^7.0.0
  #di
  get_it: ^7.1.3
  provider: 6.0.0
  #model
  json_annotation: ^4.0.1
  built_collection: ^5.0.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  built_value: ^8.0.6

dev_dependencies:
  build_runner: ^2.0.3
  pedantic: ^1.9.0
  json_serializable: ^4.1.2

flutter:
  uses-material-design: true