name: homework
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.0.0
  http: 0.13.3
dev_dependencies:
  pedantic: 1.11.1
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true

