name: lesson_21_animations_homework
description: Cocktail of the day application
version: 1.0.0+1
authors:
  - Flutter Mobile developer cource

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  http: ^0.13.0
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.22.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  koin: ^0.15.0-nullsafety.0
  koin_flutter: ^0.11.0-nullsafety.0
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  hive: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.0.3
  hive_generator: ^1.1.1

flutter:
  uses-material-design: true

